apiVersion: v1
kind: Pod
metadata:
  name: gvisor-test
spec:
  runtimeClassName: gvisor
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:latest
      command: ["dmesg"]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
          add: ["SYSLOG"]
